<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Welcome" name="Default test" tests="12" failures="2" timestamp="12 Nov 2018 14:27:10 GMT" time="0.143" errors="0">
  <testcase name="a1" time="0.029" classname="com.java.maven.piechart.report.ATest"/>
  <testcase name="a2" time="0.002" classname="com.java.maven.piechart.report.ATest"/>
  <testcase name="a3" time="0.008" classname="com.java.maven.piechart.report.ATest"/>
  <testcase name="a4" time="0.004" classname="com.java.maven.piechart.report.ATest"/>
  <testcase name="a5" time="0.003" classname="com.java.maven.piechart.report.ATest"/>
  <testcase name="b1" time="0.002" classname="com.java.maven.piechart.report.BTest"/>
  <testcase name="b4" time="0.006" classname="com.java.maven.piechart.report.BTest">
    <failure type="java.lang.AssertionError" message="B4() Method failed...!!!!">
      <![CDATA[java.lang.AssertionError: B4() Method failed...!!!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.java.maven.piechart.report.BTest.b4(BTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- b4 -->
  <testcase name="b5" time="0.003" classname="com.java.maven.piechart.report.BTest">
    <failure type="java.lang.AssertionError" message="B5() Method failed...!!!!">
      <![CDATA[java.lang.AssertionError: B5() Method failed...!!!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.java.maven.piechart.report.BTest.b5(BTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- b5 -->
  <testcase name="b6" time="0.002" classname="com.java.maven.piechart.report.BTest"/>
  <testcase name="b7" time="0.001" classname="com.java.maven.piechart.report.BTest"/>
  <testcase name="b2" time="0.001" classname="com.java.maven.piechart.report.BTest"/>
  <testcase name="b3" time="0.0" classname="com.java.maven.piechart.report.BTest">
    <skipped/>
  </testcase> <!-- b3 -->
</testsuite> <!-- Default test -->
