<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" total="12" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="143" started-at="2018-11-12T14:27:09Z" finished-at="2018-11-12T14:27:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="143" started-at="2018-11-12T14:27:09Z" finished-at="2018-11-12T14:27:09Z">
      <class name="com.java.maven.piechart.report.ATest">
        <test-method status="PASS" signature="a1()[pri:0, instance:com.java.maven.piechart.report.ATest@eff760]" name="a1" duration-ms="29" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a1 -->
        <test-method status="PASS" signature="a2()[pri:0, instance:com.java.maven.piechart.report.ATest@eff760]" name="a2" duration-ms="2" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a2 -->
        <test-method status="PASS" signature="a3()[pri:0, instance:com.java.maven.piechart.report.ATest@eff760]" name="a3" duration-ms="8" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a3 -->
        <test-method status="PASS" signature="a4()[pri:0, instance:com.java.maven.piechart.report.ATest@eff760]" name="a4" duration-ms="4" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a4 -->
        <test-method status="PASS" signature="a5()[pri:0, instance:com.java.maven.piechart.report.ATest@eff760]" name="a5" duration-ms="3" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a5 -->
      </class> <!-- com.java.maven.piechart.report.ATest -->
      <class name="com.java.maven.piechart.report.BTest">
        <test-method status="PASS" signature="b1()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b1" duration-ms="2" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b1 -->
        <test-method status="FAIL" signature="b4()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b4" duration-ms="6" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[B4() Method failed...!!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: B4() Method failed...!!!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.java.maven.piechart.report.BTest.b4(BTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b4 -->
        <test-method status="FAIL" signature="b5()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b5" duration-ms="3" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[B5() Method failed...!!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: B5() Method failed...!!!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.java.maven.piechart.report.BTest.b5(BTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b5 -->
        <test-method status="PASS" signature="b6()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b6" duration-ms="2" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b6 -->
        <test-method status="PASS" signature="b7()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b7" duration-ms="1" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b7 -->
        <test-method status="PASS" signature="b2()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b2" duration-ms="1" started-at="2018-11-12T19:57:09Z" finished-at="2018-11-12T19:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b2 -->
        <test-method status="SKIP" signature="b3()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829]" name="b3" duration-ms="0" started-at="2018-11-12T19:57:09Z" depends-on-methods="com.java.maven.piechart.report.BTest.b4" finished-at="2018-11-12T19:57:09Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BTest.b3()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BTest.b3()[pri:0, instance:com.java.maven.piechart.report.BTest@e9a829] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b3 -->
      </class> <!-- com.java.maven.piechart.report.BTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
